model:
  name: "amazon/chronos-t5-large"  
  device: "cuda"                    # "cpu" or "cuda"
  torch_dtype: "bfloat16"          
  num_samples: 20

forecasting:
  input_size: 200   
  output_size: 200   
  batch_size: 64     